development:
  adapter: postgresql
  encoding: unicode
  database: _development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: _test
  pool: 5
  username:
  password:
